name: psumathnotebooks-env
channels:
  - conda-forge
dependencies:
  - python
  - ipywidgets
  - numpy
  - sympy
  - scipy
  - pandas
  - matplotlib
  - jupyter_contrib_nbextensions
  - rise
  - pip
  